[34m[1mwandb[0m: Downloading large artifact model-checkpoints:v0, 1631.39MB. 1 files...
[34m[1mwandb[0m:   1 of 1 files downloaded.
Done. 0:0:1.9
> [32m/home/jennifer/clip_text_span/load.py[39m([92m21[39m)[36m<module>[39m[34m()[39m
[32m     20[39m [38;5;66;03m# Load the checkpoint file[39;00m
[32m---> 21[39m checkpoint = torch.load(f"{artifact_dir}/checkpoint_epoch_5.pt")
[32m     22[39m

'/home/jennifer/clip_text_span/artifacts/model-checkpoints:v0'
Traceback (most recent call last):
  File "/home/jennifer/clip_text_span/load.py", line 21, in <module>
    checkpoint = torch.load(f"{artifact_dir}/checkpoint_epoch_0.pt")
                 ^^^^^^^^^^
  File "/home/jennifer/miniconda3/envs/prsclip/lib/python3.12/bdb.py", line 100, in trace_dispatch
    return self.dispatch_line(frame)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jennifer/miniconda3/envs/prsclip/lib/python3.12/bdb.py", line 125, in dispatch_line
    if self.quitting: raise BdbQuit
                      ^^^^^^^^^^^^^
bdb.BdbQuit

If you suspect this is an IPython 9.0.2 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
